### PR TITLE
Fixed opening from console.

### PR DESCRIPTION
**Pull request by yakloinsteak**
Tested on Archlinux using console and gvim 7.3.401.

### CODE REVIEW

**Comment by lucapette** [comment]
@yakloinsteak Thank you very much for writing this. Actually, I can't merge it because it doesn't work in all the situation (on my box for example the terminal version isn't working fine). The last commit is meant to solve the problem and it is inspired by your work. So thanks again. It would be great if you can give me some feedback about the changes I made to the plugin.

**Comment by yakloinsteak** [comment]
You're welcome, and the commit only represented some quick hacking that I could only minimally test.  I'll take a look at your commit and see if I have anything to say about it.

**Comment by ruanwz** [comment]
One suggestion: the same fix is also needed for the plugin vim-jquery-doc

**Comment by lucapette** [comment]
@ruanwz Thank you for the suggestion. I've updated the README of vim-jquery-doc to make the situation clear.

@yakloinsteak I've explained how I'd like to proceed in the commit :)

**Pull request closed without merging**
